import './globals.css'
import type { Metadata } from 'next'

import { Nunito } from 'next/font/google'

const nunito = Nunito({
  weight: ['400', '700', '800'],
  subsets: ['latin'],
  variable: '--font-nunito',
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}
export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${nunito.variable}`}>{children}</body>
    </html>
  )
}
