import './globals.css'
import type { Metadata } from 'next'

import { Nunito } from 'next/font/google'

const nunito = Nunito({
  weight: ['400', '700', '800'],
  subsets: ['latin'],
  variable: '--font-nunito',
})

export const metadata: Metadata = {
  title: 'Type Weather',
  description: 'Generated by create next app',
}
export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${nunito.variable}`}>
        <div
          style={{
            backgroundImage: 'url(/images/backgrounds/background.png)',
          }}
          className="fixed flex h-full min-h-screen w-full justify-center overflow-auto bg-cover bg-center bg-no-repeat p-4"
        >
          {children}
        </div>
      </body>
    </html>
  )
}
