export const weatherCodeToDescription = {
  0: 'Céu limpo',
  1: 'Ceu claro',
  2: 'Pouco nublado',
  3: 'Encoberto',
  45: 'Nevoeiro',
  48: 'Neblina depositada',
  51: 'Chuvisco leve',
  53: 'Chuvisco moderado',
  55: 'Chuvisco denso',
  56: 'Chuvisco leve',
  57: 'Chuvisco denso',
  61: 'Chuva leve',
  63: 'Chuva moderada',
  65: 'Chuva forte',
  66: 'Chuva leve',
  67: 'Chuva pesada',
  71: 'Neve leve',
  73: 'Neve moderada',
  75: 'Neve forte',
  77: 'Grãos de neve',
  80: 'Chuva leves',
  81: 'Chuva moderadas',
  82: 'Chuva forte',
  85: 'Neve leves',
  86: 'Neve fortes',
  95: 'Trovoada',
  96: 'Trovoada leve',
  99: 'Trovoada forte',
}
